### ISSUE TITLE
Make in termux

### ISSUE THREAD

**Issue by fagci** [lwvmobile/dsd-fme#103]
Successfully built dsd-fme on termux.

What I fixed:
1. extract function `getTime()` in `src/dmr_bs.c`
2. remove `getTime()` definitions from `src/dmr_ms.c`, `src/p25p2_frame.c`
3. added `#include <strings.h>` to `src/dsd_rigctl.c`

All needed requirements got using this script:
https://pastebin.com/xatGjWc9 (https://www.reddit.com/r/RTLSDR/comments/mtef0n/use_dsd_and_librtlsdr_userland_programs_on/) with fix of replacement pthread_cancel -> pthread_exit using `(void *)` conversion.

**Comment by fagci** [comment]
![Screenshot_20230311-030654](https://user-images.githubusercontent.com/8795970/224417758-d6e26887-df2a-46ea-bbc4-c8cc0de97f81.png)

But need to setup audio output i think =)

**Comment by lwvmobile** [comment]
Oh, I just noticed the segfault at the bottom on TCP input attempt. That may not work then.

**Comment by fagci** [comment]
![Screenshot_20230311-033409](https://user-images.githubusercontent.com/8795970/224423117-ad909f1e-943e-43af-b980-4b595017af6f.png)

Yes, works through tcp connection, but no sound for now. Was weak signal + maybe unloaded sdr++ app by Android.

**Comment by lwvmobile** [comment]
Oh, well, looks like those Cap+ CSBKs are coming in clean, but they show idle on all channels. Also keep in mind, if there is activity on one of the other channels you aren't parked on, it won't decode audio from those, but you can trunk it if you set up a csv file and turn on the RIGCTL server inside of SDR++ and connect to that as well. Have you seen any indication of voice yet (VLC, VC1-6)?  I'm going to not include the first screenshot, those bad decodes could all be bad with that many errors present.

If it doesn't route out audio to the default device, then I have no idea how you would change it to another output device. On FME, I stripped out port audio and OSS from the previous versions and used pulse audio for output. Usually in the Linux Desktop Environment we would just use pulse audio volume control or pulsemixer to route audio in and out of different outputs and so on.

If you want to see more on possibly trunking that Cap+ system, see the examples here:
https://github.com/lwvmobile/dsd-fme/tree/main/examples

**Comment by fagci** [comment]
Yup, VLC is in logs:
```
03:57:55 Sync: +DMR   slot1  [slot2] | Color Code=02 | VLC
 SLOT 2 TGT=207 SRC=30802 Cap+ Group Call  Cap+ R-Ch 5
03:57:55 Sync: +DMR  [slot1]  slot2  | Color Code=02 | CSBK
 Capacity Plus Channel Status - FL: 3 TS: 0 RS: 0 - Rest Channel 5 - Single Block
  Ch1: Idle Ch2: Idle Ch3: Idle Ch4: Idle
  Ch5: Rest Ch6:  207 Ch7: Idle Ch8: Idle
 SLCO Capacity Plus Site: 1 - Rest Channel 5 - RS: 00                            03:57:55 Sync: +DMR   slot1  [slot2] | Color Code=02 | VLC
 SLOT 2 TGT=207 SRC=30802 Cap+ Group Call  Cap+ R-Ch 5
03:57:55 Sync: +DMR  [slot1]  slot2  | Color Code=02 | CSBK
 Capacity Plus Channel Status - FL: 3 TS: 0 RS: 0 - Rest Channel 5 - Single Block
  Ch1: Idle Ch2: Idle Ch3: Idle Ch4: Idle
  Ch5: Rest Ch6:  207 Ch7: Idle Ch8: Idle
03:57:55 Sync: +DMR   slot1  [slot2] | Color Code=02 | VLC                        SLOT 2 TGT=207 SRC=30802 Cap+ Group Call  Cap+ R-Ch 5
03:57:55 Sync: +DMR  [slot1]  slot2  | Color Code=02 | CSBK
 Capacity Plus Channel Status - FL: 3 TS: 0 RS: 0 - Rest Channel 5 - Single Block
  Ch1: Idle Ch2: Idle Ch3: Idle Ch4: Idle
  Ch5: Rest Ch6:  207 Ch7: Idle Ch8: Idle
 SLCO Capacity Plus Site: 1 - Rest Channel 5 - RS: 00
03:57:55 Sync: +DMR   slot1  [slot2] | Color Code=02 | VLC
 SLOT 2 TGT=207 SRC=30802 Cap+ Group Call  Cap+ R-Ch 5
03:57:55 Sync: +DMR  [slot1]  slot2  | Color Code=02 | CSBK
 Capacity Plus Channel Status - FL: 3 TS: 0 RS: 0 - Rest Channel 5 - Single Block
  Ch1: Idle Ch2: Idle Ch3: Idle Ch4: Idle
  Ch5: Rest Ch6:  207 Ch7: Idle Ch8: Idle
zsh: segmentation fault  dsd-fme -i tcp -w /sdcard/speech4.wav
```

Will try setup properly. Thank you! =)

**Comment by lwvmobile** [comment]
I had written a reply to this earlier, but apparently it didn't go through, probably because I closed the window without hitting send or something dumb, but if you can't get the audio to play properly (keep in mind the audio backend has been drastically changed from the szechyjs and louiserigherve branches) then depending on which particular backend you need, you MIGHT be able to use the lite/aero branch since I put the OSS handling back into that one. If you need portaudio, then this will not work.

Alternatively, you could use a null output and have it save the wav files to the current directories WAV file folder by using a command similar to `dsd-fme -i tcp -o null -P`  and that will save slot 1 and slot 2 to seperate wav files. If you can use the ncurses terminal, you could get per call wav files as well. You just won't be able to hear it play back in real time this way.

To be honest, I don't think the `-w filename.wav` option will work correctly anymore on TDMA, at best it will just record slot 1 activity and not slot 2, or it may just crash, I'm not entirely sure.

**Comment by fagci** [comment]
Don't know, why, but crashes anyway.
[dsdfme-strace.log](https://github.com/lwvmobile/dsd-fme/files/10948554/dsdfme-strace.log)

Will use just dsd, as it works on termux. Thank you.
