### ISSUE TITLE
Not able to compile new version of dsd-fme

### ISSUE THREAD

**Issue by amitpathania** [lwvmobile/dsd-fme#109]
I have been trying to compile new version of dsd-fme using following steps:-
git clone https://github.com/lwvmobile/dsd-fme
cd dsd-fme
sudo cp tone8.wav /usr/share/
sudo cp tone24.wav /usr/share/
sudo cp tone48.wav /usr/share/
sudo chmod 777 /usr/share/tone8.wav
sudo chmod 777 /usr/share/tone24.wav
sudo chmod 777 /usr/share/tone48.wav
mkdir build
cd build
cmake ..
make -j `nproc`
sudo make install
sudo ldconfig
------------------------------------------------------------------------------------------------------
I am getting following error while running make -j `nproc` command:-
----------------------------------------------------------------------------------------------------------
help2man: can't get `--help' info from /home/star/Documents/dsd-fme/build/dsd-fme
Try `--no-discard-stderr' if option outputs to stderr
CMakeFiles/dsd-fme.dir/build.make:1842: recipe for target 'dsd-fme' failed
make[2]: *** [dsd-fme] Error 2
make[2]: *** Deleting file 'dsd-fme'
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/dsd-fme.dir/all' failed
make[1]: *** [CMakeFiles/dsd-fme.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lwvmobile** [comment]
Which distro/environment/version are you using to compile with? The error seems to suggest a problem with help2man, but I seem to recall having fixed that error a long time ago in the code by changing the help section from fprintf back to printf, but that was quite a while ago, and I haven't seen any other issues come up based on it.

If all else fails, you might try to open the CMakeLists.txt file and remove lines 53-65 and delete the build folder, and run cmake and make again, and see if that works. Or you could uninstall the package help2man so it doesn't error out on this step.

https://github.com/lwvmobile/dsd-fme/blob/main/CMakeLists.txt

**Comment by amitpathania** [comment]
I am using Ubuntu 18

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 2022.08.02 LTS (Cubic 2022-08-02 07:55)
Release:	18.04
Codename:	bionic

**Comment by lwvmobile** [comment]
Well, it says it failed on help2man, but I do wonder if that is the issue, or if some other dependency wasn't met. I just installed help2man in my Ubuntu 18 VM and make a clean build without issues. Have you installed the dependencies yet, or just manually run the compile/install without installing dependencies yet?

```
sudo apt update
sudo apt install libpulse-dev pavucontrol libsndfile1-dev libfftw3-dev liblapack-dev socat libusb-1.0-0-dev libncurses5 libncurses5-dev rtl-sdr librtlsdr-dev libusb-1.0-0-dev cmake git wget make build-essential libitpp-dev libncursesw5-dev
```

Also, might be worth a shot to just try to uninstall help2man if you have that package installed with 

`sudo apt uninstall help2man`

but I have a feelign that isn't the issue. Probably didn't build due to dependencies required. Try installing the above, delete the build folder, and start again at mkdir build while inside the dsd-fme folder.

**Comment by amitpathania** [comment]
I have uninstalled help2man and now its getting compiled.

**Comment by lwvmobile** [comment]
Okay, just to clarify, it is compiled now, and running?
