### ISSUE TITLE
Hashed TG Keys Not Loading Correctly Due to Variable Type Error;

### ISSUE THREAD

**Issue by Yorch23** [lwvmobile/dsd-fme#112]
Hello
comment when entering TG with length 7, B-P KEY doesn't work.
Example:
TG=2025000 KEY=44
Result in terminal
Logging Frame Payload to console
**Hashed Key [47331] [00044]**
Enabling NCurses Terminal.
OSS Input /dev/dsp.
OSS Output /dev/dsp.
Audio In/Out Device: /dev/dsp

Greetings

**Comment by lwvmobile** [comment]
Actually, that is the correct behavior, thus the HASHED value.

What is happening, in the import, if the TG value is larger than 16-bits (0xFFFF or decimal value 65535) then it will hash the value in a CRC16 function. Likewise, when DMR decoding sees a TG value larger than 16-bits, it will hash the value for it as well and make a comparison to see if a key value needs to be loaded from the array at that position for BP key decoding.

What has went wrong: I did some testing, and realized it isn't actually loading a key vs the hashed value, because the variable type of the hash later on when checking against it is a uint16_t, which would usually be okay, but its also being assigned an initial value from a 24-bit TG value, so its truncated to 16-bits and not working correctly. I'll have a fix for this issue in the code by the weekend, and barring any other major issues, I'll try to issue an updated precompiled version as well on the weekend sometime.

**Comment by lwvmobile** [comment]
Incorrect variable:
https://github.com/lwvmobile/dsd-fme/blob/ba0e422f23e1f5eead3a9660e5b7cbddf1dcbb23/src/dsd_mbe.c#L144

needs to be uint32_t in this instance since this variable is assigned a 24-bit TG value prior to being hashed to 16-bits.

**Comment by Yorch23** [comment]
Hi, great job, it works perfectly, V2.0.0-75, it's up to you to close the matter.
Thank you
Regards

**Comment by lwvmobile** [comment]
This fix is also available now in the precompiled RC5d release.
https://github.com/lwvmobile/dsd-fme/releases/tag/win32-rc5
