### ISSUE TITLE
ERROR opening socket on WSL2 or linux in VM box

### ISSUE THREAD

**Issue by maximklakov** [lwvmobile/dsd-fme#117]
I'm trying to use latest dsd-fme with SDR++ network sink, but when I'm launching 
`dsd-fme -N 2>test_run.log -i tcp`

I'm getting:
```
Enabling NCurses Terminal.
TCP Direct Link: localhost:7355
ERROR opening socket
TCP Connection Failure - Using Pulse Audio Input.
```

I've tried in on Kali linux in a Virtual Box and on wsl2, but the error is the same.
I've checked SDR++ network sink with VLC audio player, and it looks like it works fine
I've tried different port settings with no luck
I've tried to use nc (nc -4 -l 7355   and    nc -4 -v localhost 7355) - that works fine, meaning port is not used.

Can you please help me?

**Comment by maximklakov** [comment]
I've tried SDRpp on my linux VM, but it is very laggy
I'm going to use windows in future, so the best way would be to run it in wsl or cygwin.
It looks like the message below appears right after the start of the program:
TCP Direct Link: localhost:7355
ERROR opening socket
TCP Connection Failure - Using Pulse Audio Input.

Does it mean I need to start network sink first, and than run dsd to connect to that sink?
or will it automatically connect to the sink when it will be started?

**Comment by lwvmobile** [comment]
> I've tried SDRpp on my linux VM, but it is very laggy
Most likely due to lack of host resources (may need more CPU core allocation) or more likely, lack of any real hardware graphic acceleration in the VM. 

> I'm going to use windows in future, so the best way would be to run it in wsl or cygwin.

I can't really tell you about running it under WSL, I really never tried it before. I seem to recall others needing to do extra setups to get pulse audio output to work properly from it. See the wiki for that, but I cannot verify its accuracy regarding WSL. I would just run it under Cygwin if you want to compile it yourself. Alternatively, there is a release compiled cygwin version available. Its kept pretty well current up to date with the source code. To use it, I recommend looking at the bat files inside of the zip folder.

https://github.com/lwvmobile/dsd-fme/releases/tag/win32-rc5

> Does it mean I need to start network sink first, and than run dsd to connect to that sink?
> or will it automatically connect to the sink when it will be started?

Yes, the sink needs to be started first inside of SDR++, and then DSD-FME will connect to it only if it is started. In this instance, SDR++ is the server, and DSD-FME is the client.

**Comment by maximklakov** [comment]
All right, It looks like there is dome configuration should be done on Host machine
1. First of all I've added Firewall rulefor inbound and outbound traffic on this port (might not need this):
New-NetFirewallRule -DisplayName "WSL2 Port Bridge" -Direction Outbound -Action Allow -Protocol TCP -LocalPort 7355
New-NetFirewallRule -DisplayName "WSL2 Port Bridge" -Direction Inbound -Action Allow -Protocol TCP -LocalPort 7355

2. get IP address of vEthernet (WSL) adapter of your **host** machine using ipconfig.
3. put host machine IP adress to SDR++ (do not use 127.0.0.1 or localhost - it does not work)
4. run dsd-fme -N -i tcp:<host-ip>:7355

That's it - now it works fine.
Issue can be closed, but please do not delete it - it might be helpful for others.
