### ISSUE TITLE
Output in WINDOWS (-o)

### ISSUE THREAD

**Issue by LoveScanner** [lwvmobile/dsd-fme#124]
How do I see in Windows OS the device path of the dedicated sound card through which I want to transfer the sound?
(I tried through the device manager and it didn't work)

**Comment by lwvmobile** [comment]
There is no -o options for specifying a windows audio device. Depending on which version of Windows you are using, what you will want to do is open the Volume Mixer while DSD-FME is running with its default -o setting, which should be for Windows/Cygwin /dev/dsp and route the audio out of the correct audio device.

![Screenshot_85](https://user-images.githubusercontent.com/59371473/236691902-5cd4b348-2764-4e3f-9bf7-9810310b9ab4.png)

**Comment by LoveScanner** [comment]
Windows 11 
I want to stream the sound to a specific card
Is it possible on this OS?

**Comment by lwvmobile** [comment]
Yeah, just open the volume mixer, pictured above while dsd-fme-aero is running, then click the output device for that application stream, and tell it which device you want the audio to play out of. That should be it. Worst case scenario, if it doesn't play back audio to the device you pick, you may have to close dsd-fme and restart it and then it should always go to that device.

Otherwise, just run it with the default options for output at the CLI, as in, don't enter anything for -o, just don't use that switch for audio playback.

**Comment by lwvmobile** [comment]
Just to update, did you get this worked out? Did you need any more assistance with it? If you got it figured out, let me know so I can go ahead and close this issue.

**Comment by LoveScanner** [comment]
> There is no -o options for specifying a windows audio device. Depending on which version of Windows you are using, what you will want to do is open the Volume Mixer while DSD-FME is running with its default -o setting, which should be for Windows/Cygwin /dev/dsp and route the audio out of the correct audio device.
> 
> ![Screenshot_85](https://user-images.githubusercontent.com/59371473/236691902-5cd4b348-2764-4e3f-9bf7-9810310b9ab4.png)

This idea helped me
Thank you

**Comment by lwvmobile** [comment]
Alrighty, I'll just go ahead and close as completed then.
