### ISSUE TITLE
Crash on windows (pulseaudio out)

### ISSUE THREAD

**Issue by rlex** [lwvmobile/dsd-fme#129]
Hello! After updating to aero-100, got following error while trying to open menu: 

```
Assertion 'p' failed at /usr/src/ports/pulseaudio/pulseaudio-11.1-1.i686/src/pulseaudio-11.1/src/pulse/simple.c:273, function pa_simple_write(). Aborting.
                                                                                                           0 [main] dsd-fme-aero 709 cygwin_exception::open_stackdumpfile: Dumping stack trace to dsd-fme-aero.exe.stackdump
```

my arguments for launch:
 -i tcp:127.0.0.1:7355 -o pulse -N -fi

This also happens when dsd-fme is trying to send data to audio output, it seems.

Win10, just in case.

**Comment by rlex** [comment]
...and as soon as i posted this it stopped. Well, probably some local issue.

**Comment by lwvmobile** [comment]
If you are going to use the pulse audio output in Windows, you have to start the pulse audio server backend first with the `1a - start-pulse-audio-backend.bat` file before starting DSD-FME, otherwise, you can remove the `-o pulse` of the command and use the other audio handling, which will work fine as well, but if there are voices in both slots in TDMA, it will only play one of them.

**Comment by lwvmobile** [comment]
Also, just gauging by your command, if you are using the `-fi` switch for NXDN48, you definitely do not need to use the `-o pulse` option.
