### ISSUE TITLE
P25 Soft ID

### ISSUE THREAD

**Issue by Dmedia3412** [lwvmobile/dsd-fme#166]
Is it possible to add Soft ID decodding?

**Comment by lwvmobile** [comment]
Not sure what you mean by Soft ID. Do you mean special addresses like the FNE?

**Comment by Dmedia3412** [comment]
Soft ID/Username, Located in Radio wide / User Information and Passwords. Motorola APX Series CPS.

Transmitted to LSD1 LSD2 in 3 superframes in a circle.
SF1
LSD1 02 08 (Header?)
LSD2 FF FF (SID1)
SF2
LSD1 FF FF (SID2)
LSD2 FF FF (SID3)
SF3
LSD1 FF FF (SID4)
LSD2 00 00 (CRC?)
SF4
LSD1 02 08 (Header?)
LSD2 FF FF (SID1)
SF5
LSD1 FF FF (SID2)
LSD2 FF FF (SID3)
SF6
LSD1 FF FF (SID4)
LSD2 00 00 (CRC?)

Contains up to 8 random ASCI characters. Reminds me of talker alias DMR.

I couldn't find any description, I think this is Motorola's proprietary data.

**Comment by lwvmobile** [comment]
I don't know if LSD carries any sort of Talker Alias or anything like that. I had it dump the LSD for me, and the closest I got on all the samples I had was an 'hq' with the rest of the LSD tranlating to gibberish because its not ASCII format. 

```
17:02:06 Sync: +P25p1  nac: [ 293] src: [       0] tg: [    0]  HDU
 HDU  ALG ID: 0x80 KEY ID: 0x0000 MI: 0x0000000000000000
17:02:06 Sync: +P25p1  nac: [ 293] src: [       0] tg: [    0]  LDU1  
 Group Voice Channel User - Group 1 Source 1 LSD: 8A 68 (�h)
17:02:06 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU2  
 LDU2 ALG ID: 0x80 KEY ID: 0x0000 MI: 0x0000000000000000 LSD: 71 F0 (q�)
17:02:06 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU1  
 Group Voice Channel User - Group 1 Source 1 LSD: 12 12 ()
17:02:07 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU2  
 LDU2 ALG ID: 0x80 KEY ID: 0x0000 MI: 0x0000000000000000 LSD: 12 8A (�)
17:02:07 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU1  
 Group Voice Channel User - Group 1 Source 1 LSD: 68 71 (hq)
17:02:07 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU2  
 LDU2 ALG ID: 0x80 KEY ID: 0x0000 MI: 0x0000000000000000 LSD: F0 12 (�)
17:02:07 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU1  
 Group Voice Channel User - Group 1 Source 1 LSD: 12 12 ()
17:02:07 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU2  
 LDU2 ALG ID: 0x80 KEY ID: 0x0000 MI: 0x0000000000000000 LSD: 8A 68 (�h)
17:02:08 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU1  
 Group Voice Channel User - Group 1 Source 1 LSD: 71 F0 (q�)
17:02:08 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU2  
 LDU2 ALG ID: 0x80 KEY ID: 0x0000 MI: 0x0000000000000000 LSD: 12 12 ()
17:02:08 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU1  
 Group Voice Channel User - Group 1 Source 1 LSD: 12 8A (�)
17:02:08 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU2  
 LDU2 ALG ID: 0x80 KEY ID: 0x0000 MI: 0x0000000000000000 LSD: 68 71 (hq)
17:02:08 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU1  
 Group Voice Channel User - Group 1 Source 1 LSD: F0 12 (�)
17:02:08 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU2  
 LDU2 ALG ID: 0x80 KEY ID: 0x0000 MI: 0x0000000000000000 LSD: 12 12 ()
17:02:09 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU1  
 Group Voice Channel User - Group 1 Source 1 LSD: 8A 68 (�h)
17:02:09 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU2  
 LDU2 ALG ID: 0x80 KEY ID: 0x0000 MI: 0x0000000000000000 LSD: 71 F0 (q�)
17:02:09 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU1  
 Group Voice Channel User - Group 1 Source 1 LSD: 12 12 ()
17:02:09 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU2  
 LDU2 ALG ID: 0x80 KEY ID: 0x0000 MI: 0x0000000000000000 LSD: 12 8A (�)
17:02:09 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU1  
 Group Voice Channel User - Group 1 Source 1 LSD: 68 71 (hq)
17:02:09 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU2  
 LDU2 ALG ID: 0x80 KEY ID: 0x0000 MI: 0x0000000000000000 LSD: F0 12 (�)
17:02:10 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU1  
 Group Voice Channel User - Group 1 Source 1 LSD: 12 12 ()
17:02:10 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU2  
 LDU2 ALG ID: 0x80 KEY ID: 0x0000 MI: 0x0000000000000000 LSD: 8A 68 (�h)
17:02:10 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU1  
 Group Voice Channel User - Group 1 Source 1 LSD: 71 F0 (q�)
17:02:10 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU2  
 LDU2 ALG ID: 0x80 KEY ID: 0x0000 MI: 0x0000000000000000 LSD: 12 12 ()
17:02:10 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU1  
 Group Voice Channel User - Group 1 Source 1 LSD: 12 8A (�)
17:02:11 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU2  
 LDU2 ALG ID: 0x80 KEY ID: 0x0000 MI: 0x0000000000000000 LSD: 68 71 (hq)
17:02:11 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU1  
 Group Voice Channel User - Group 1 Source 1 LSD: F0 12 (�)
17:02:11 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  TDU

```

I suppose the LSD data is there for something, but the TIA manual doesn't seem to have any relevant information regarding it, other than its not defined in the CAI.

![Screenshot from 2023-10-04 17-10-11](https://github.com/lwvmobile/dsd-fme/assets/59371473/866d5a70-d962-4c74-8f87-28439bfaf750)



If there is a form of Talker Alias in P25p1, it could be in link control word format, and under a specific opcode, like it is in NXDN and DMR. I really have no idea. When you have that feature enabled, do you see any unknown LCW formats and the payloads on them, do they seem to be ASCII characters. Usually, you'll want to look at each octet and see if it falls between hex 0x20 and 0x7E for ascii, and if its UTF-16, usually, it'll be like 0x00 0x20 with an extra 0x00 byte unless its using diacritical extended roman alphabet, eastern languages, etc.

![ASCII-Table-wide](https://github.com/lwvmobile/dsd-fme/assets/59371473/bb535483-8d60-4ca0-b9ca-8da13ab41a89)

**Comment by Dmedia3412** [comment]
I don't see LSD1-2 in DSD-FME

This is what I see in DSD 1.8.4 in BIN format

nac:  293 tg:     0  LDU1  e:
lsd1: 00000010 lsd2: 00101000
nac:  293 tg:     1  LDU2  e:
lsd1: 01010010 lsd2: 00110110
nac:  293 tg:     1  LDU1  e:
lsd1: 01010111 lsd2: 01000010
nac:  293 tg:     1  LDU2  e:
lsd1: 01010000 lsd2: 00100000
nac:  293 tg:     1  LDU1  e:
lsd1: 00100000 lsd2: 00100000
nac:  293 tg:     1  LDU2  e:
lsd1: 00100001 lsd2: 11011110
nac:  293 tg:     1  LDU1  e:
lsd1: 00000010 lsd2: 00001000
nac:  293 tg:     1  LDU2  e:
lsd1: 01010010 lsd2: 00110100
nac:  293 tg:     1  LDU1  e:
lsd1: 01010111 lsd2: 01000010
nac:  293 tg:     1  LDU2  e:
lsd1: 01010000 lsd2: 00100000
nac:  293 tg:     1  LDU1  e:
lsd1: 00100000 lsd2: 00100000
nac:  293 tg:     1  LDU2  e:
lsd1: 00100001 lsd2: 11001110
nac:  293 tg:     1  TDU

That's how I see it.

SF1; LDU1
BIN: lsd1: 00000010 lsd2: 00101000 
HEX: lsd1: 02 lsd2: 08

SF1;LDU2
BIN: lsd1: 01010010 lsd2: 00110110
HEX: lsd1: 52 lsd2: 34
ASCII: lsd1: "R" lsd2: "4"

SF2;LDU1
BIN: lsd1: 01010111 lsd2: 01000010
HEX: lsd1: 57 lsd2: 42
ASCII: lsd1: "W" lsd2: "B"

SF2;LDU2
BIN: lsd1: 01010000 lsd2: 00100000
HEX: lsd1: 50 lsd2: 20
ASCII: lsd1: "P" lsd2: " "

SF3;LDU1
BIN: lsd1: 00100000 lsd2: 00100000
HEX: lsd1: 20 lsd2: 20
ASCII: lsd1: " " lsd2: " "

SF3;LDU2
BIN: lsd1: 00100001 lsd2: 11011110
HEX: lsd1: 21 lsd2: DE

**Comment by lwvmobile** [comment]
I don't currently have the code to expose the LSD up officially, it was just something I coded in quickly to dump LSD and see if I could find anything in it with the samples I have.

If you can send a sample wav file of that particular radio, or other radios that also have soft id enabled, I'll examine them and see what I can do. I'm assuming that ASCII there is the same as your call sign, or soft id?

You can upload any wavs you have here if you don't have anywhere else to upload them to.

https://ufile.io/

**Comment by Dmedia3412** [comment]
https://mega.nz/file/6QRxhSyS#JWCinGQ_S-SO5qUyg666zISo6rxBhyX7kTztnZBuzLI

These are 3 SDRSharp Baseband records.
The file names correspond to the Soft id.

**Comment by lwvmobile** [comment]
Okay thanks, I'll try to take a look at it sometime soon and see what I can work out.

**Comment by lwvmobile** [comment]
Okay, I see what you are talking about now. I had a conversion error when dealing with LSD as a string. 

```
17:54:19 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU1  
lsd1: 00000010 lsd2: 00001000 LSD: 02 08 )
 Group Voice Channel User - Group 1 Source 1
17:54:19 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU2  
lsd1: 01000001 lsd2: 01000010 LSD: 41 42 (AB)
 LDU2 ALG ID: 0x80 KEY ID: 0x0000 MI: 0x0000000000000000
17:54:19 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU1  
lsd1: 01000011 lsd2: 01000100 LSD: 43 44 (CD)
 Group Voice Channel User - Group 1 Source 1
17:54:19 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU2  
lsd1: 01000101 lsd2: 01000110 LSD: 45 46 (EF)
 LDU2 ALG ID: 0x80 KEY ID: 0x0000 MI: 0x0000000000000000
17:54:20 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU1  
lsd1: 00100000 lsd2: 00100000 LSD: 20 20 (  )
 Group Voice Channel User - Group 1 Source 1
17:54:20 Sync: +P25p1  nac: [ 293] src: [       1] tg: [    1]  LDU2  
lsd1: 10011111 lsd2: 10011010 LSD: 9F 9A (��)

```

The samples had a lot of decoding errors on my end though, lots of voice errors and subsequently, errors in the LSD fields.

**Comment by Dmedia3412** [comment]
I think that SF3;LDU2 is some kind of checksum, but I still don’t understand how it is calculated. This is not part of the Soft-ID text.

I can rewrite my examples if I'm having trouble decoding.

**Comment by lwvmobile** [comment]
Yeah, its possible that it could be a CRC16 checksum, it seems to change depending on what the values are for the SOFT ID. I didn't really get around to trying it to see if it passed a CRC16 or not, but I did put code based on your observations and what I observed in LSD in the audio_work branch and its available now for compilation. What I came out with is that 0x02 is the opcode, and that 0x08 is the length of octets in the soft id. That could be purely coincidence, but it seldomly seems to randomly trigger on anything that doesn't have a soft id, but has some other info in the LSD.

More importantly though, LSD never had its FEC implemented, it has some cyclic parity bits for error correction, so that would be more important to get worked out at some point in the future. Right now, its just going to dump whatever is there as is straight off the air without the error correction.

**Comment by Dmedia3412** [comment]
TIA writes that LRRPs are sent to LSD in the same way, this is also worth checking.

The implementation of cyclic parity bits for error correction can be seen in the mmdvm-host code. I see that Soft-ID is transmitted from P25Reflector, but SF3,LSD2 is always 00 00 so my APX does not show Soft-ID.
If I force the correct "CRC" to be sent then the Soft-ID is displayed on my radio. I would like to understand the checksum and how to generate it from Soft-ID.

**Comment by lwvmobile** [comment]
I put a patched exe zip file in the latest release under assets, if you want to try it out. If you copy and paste it into your dsd-fme forlder (assuming you are using Windows anyways) there is some Soft ID decoding that works on the samples you provided. Its also available now in the audio_work branch for compiling on Linux. Still doesn't have any forward error correction, but at least it'll check the parity and make sure the LSD elements are correct.

To see the LSD data in the console or log, you'll need to run with the `-Z` option, otherwise, it'll populate the D XTRA field in the ncurses terminal with anything that it thinks is a soft id. It may also put other things in there as well, if it also by chance carries the hex value 0x02 in that opcode looking field.

https://github.com/lwvmobile/dsd-fme/releases/tag/20230915

**Comment by Dmedia3412** [comment]
Yes it works, but there are a lot of errors on a weak signal.

If the signal is strong it works well.

Later I will record a video and post it here to confirm that this already works well for a strong signal.

**Comment by Dmedia3412** [comment]
I would add Soft ID to Call History.
Is this possible?

**Comment by lwvmobile** [comment]
Maybe at some point, but it being broken into segments makes it a bit complicated, and also, I'm not entirely sure now if other information isn't conveyed in the same 0x02 opcode. That could be, if it isn't used solely for SOFT ID, some indicator like the start of a message on longer form messages, like LRRP, etc. With the code enabled right now, I get random strings of nonsense in the call field on different Phase 1 calls that don't make any sense.

**Comment by lwvmobile** [comment]
Okay, I think the random garbage strings I was getting is due to encryption. I forgot that encryption is also applied to the LSD octets as well (and optionally the LCW on LDU1) so just for now, I am just going to zero out the LSD when enc is applied. In the future, if its a method supported by DSD-FME, well use the generated keystream and apply it to the LSD as well, but I'd have to refactor how RC4 works (currently, its on-demand, which is fine, but not the most efficient way to use it)
