### ISSUE TITLE
Decoding multiple channels at once

### ISSUE THREAD

**Issue by kantooon** [lwvmobile/dsd-fme#167]
Hello and thanks for your software additions, it is very useful to me for testing an amateur DMR tier III system.
My question is, can dsd-fme receive and decode multiple channels at once (within the bandwidth of the RTL device of course)?
I'd like to be able to follow the control channel traffic while I'm decoding voice on a payload channel (which itself is on a different physical channel), in order to monitor other TV_GRANT and PV_GRANT happening and switch to them in real time if the DST address matches a GID.
I know this is technically possible, and I tried to look at the source but I'm not a C guru and I didn't find the answer.

**Comment by lwvmobile** [comment]
Well, the way its currently coded, it can only handle a single a single RF channel at a time in terms of control channel/payload channel following. It has to leave the control channel to tune to the payload channel, and then make a decision to return to the control channel or follow to the next voice grant from there. The audio_work branch has some TG hold features implemented that can allow dsd-fme to jump from one payload channel to another, as long as a call grant exists on the payload channel to push traffic forward, otherwise, it'll have to wait on the P_CLEAR or signal loss, return to the CC, and then get a new voice channel assignment.

I suppose some modifications to the source code could be made that would allow one instance of DSD-FME to always listen to the control channel, and direct a second instance of DSD-FME (via rigctl or the udp port built into rtl_fm implementation) to various channels, or expand it outwards to allow for multiple slave instances of DSD-FME, but that would require some modifications that break the way it currently works, I don't know if I could easily implement a method to retain the current handling, and also allow an expanded handling as described.

Alternatively, if the system, or any number of frequencies, were in the confines of the bandwidth of one device (rtl, or airpsy, etc) and you were to use SDR++ with its network sink and set up multiple radios in that software and pipe each out of a different TCP port, then you could feasible open one instance of DSD-FME for every payload channel and just monitor the payload channels all at once (or as many as you could cram into the bandwidth) and just skip the control channel entirely, just depends on if the control channel is a single TSCC (standard) with a voice slot, or a double TSCC (CapMax) with no voice on it. Its not uncommon for me personally to open SDR++, park in a range, and open multiple instances to monitor multiple frequencies with multiple instances of DSD-FME, but usually, they are conventional, but there isn't anything keeping you from doing it with multiple trunking channels, that way you don't miss any calls if you can cover the entire spread.

This image got compressed a bit too much and resized, but here is an example a user sent me quite a while back where they are monitoring 5 NXDN traffic channels in a small window all at once and just skipping over monitoring the control channel. They really didn't want to miss a single call.

![1683877558244](https://github.com/lwvmobile/dsd-fme/assets/59371473/47d12488-bc99-451d-ba09-7c8e7a41c755)

**Comment by kantooon** [comment]
Thanks for the detailed answers! It never occured to me to use multiple instances with SDR++, it's a good idea. What I'm not sure of with the current implementation, if one instance is monitoring the CC, won't it jump straight away too to a payload channel as soon as a TV/PV_GRANT is received?
What I was thinking of initially, was to demodulate directly in DSD multiple channels based on the CSV file frequencies, using a sample rotator or a polyphase channelizer., and then you don't need a network layer between multiple instances since it's all internal, and also one channel can always be monitored as the CC without retuning the device. Then again since I'm not that great at C, this is just an idea (I'd do this myself if I had the time to learn the codebase).
Cheers and keep up the good work!

**Comment by lwvmobile** [comment]
> if one instance is monitoring the CC, won't it jump straight away too to a payload channel as soon as a TV/PV_GRANT is received?

Not unless DSD-FME has the RIGCTL port set with the `-U 4532` option or doesn't have the `-T` option set for trunking, then it will not tune. You can leave both off the command and just passively listen to the control channel without it attempting to tune.



> What I was thinking of initially, was to demodulate directly in DSD multiple channels based on the CSV file frequencies, using a sample rotator or a polyphase channelizer., and then you don't need a network layer between multiple instances since it's all internal, and also one channel can always be monitored as the CC without retuning the device. Then again since I'm not that great at C, this is just an idea (I'd do this myself if I had the time to learn the codebase).
> Cheers and keep up the good work!

Well, good luck with that if you want to give it a go. The thing about not being good with C, I'm not good with C, and that hasn't stopped me from fumbling around and figuring it out over time. It was pretty ugly to start with a couple years ago, but I've figured out a lot as I've gone along. I still make mistakes and write some ugly bits of code, but I don't let that stop me. Best way to learn is just to jump in and try things.

**Comment by kantooon** [comment]
Thanks for the information! It works great in the setup you described.
