### ISSUE TITLE
Possible features - sharing some ideas

### ISSUE THREAD

**Issue by kantooon** [lwvmobile/dsd-fme#169]
Hey there! I have some ideas I want to share with you about possible features. Feel free to take any of this or none at all. I'd work on this myself but I'm currently digging the tunnel from the other end.

1. Qt interface: it's easier to click on things than memorize shortcuts
2. Channel view: either read the logical channel -> frequency announcements by the BS (if it broadcasts that info) or populate user supplied information.
3. Click on call view item to follow a call on a certain channel.
4. Priority groups: with priority either supplied by user or announced by the BS, if following a call and a higher priority call is announced, drop the current call and switch to the higher prio one
5. Scan group lists: user could supply a list of groups, when a grant is given for one of those groups, follow the call, otherwise rest on CC
6. Announcements of TSCC or nearby sites (useful for roaming when in motion)
7. List of MS currently registered on system, maybe also all signalling addressed to that MS

I've attached a print screen to my current DMR tier 3 management interface (WIP and more to come as I figure it out), I'm sure you can find other useful things that might be displayed.

![DMRTrunkViewer1](https://github.com/lwvmobile/dsd-fme/assets/968724/521b5787-42c9-4e3c-8d63-8854c92efc62)

**Comment by lwvmobile** [comment]
Yeah, I mean, all of those things are really good ideas, but when it comes to implementing them, it would be quite difficult to fundamentally change the entire process of the dsd source code to make all of those things happen. It could be done, but then you begin to think its probably better to start a project from scratch where you can plan for and think all these features out, instead of continually tacking things into the dsd source code (like I do here with DSD-FME) that can work within the bounds of the dsd source code as it is without major overhauls and breaking the way things work right now.

So, I mean, if anybody wants to tackle a project like that, anybody can fork and start coding, or start from scratch and borrow decoding elements from current code (this project, or others) when possible but that's certainly not a short term goal of mine. I have considered things like this as a long term goal or project, but it'll be one I won't be starting today.

**Comment by kantooon** [comment]
Yeah no worries, like I said these were just some ideas I had, but I can see that the current code has a completely different code structure and it might be difficult to change it. Good luck anyway, this project is very useful!
