### ISSUE TITLE
Feature Request: SRC contactlist

### ISSUE THREAD

**Issue by WiredLife** [lwvmobile/dsd-fme#171]
Hello,
you did a great work on this project and i really appreciate it <3
Is it possible to add a contactlist in form of a txt file where the SRC maps to a name?
Would be very nice to have names in the Call History and recorded wav files.

**Comment by lwvmobile** [comment]
It should already do that, if you use src addresses in your group.csv file instead of tgt addresses, it'll display the src name you've provided, just make sure to set it up in a manner like you would a group.csv file, it will act on any modes supplied, A,B,DE, etc, and allow or block accordingly if those values are set. Also keep in mind if you have a system where a tgt address can clash with a src address, it may display the name with the tgt address as the handling for names or labels aren't seperated, it was just a dirty addition to have it do so either way. Also, keep in mind that there is a limit on how many names you can import, in Windows(cygwin), I believe the value is 1023 currently, so massive group.csv files may cause a crash.

**Comment by lwvmobile** [comment]
Does that adequately answer your question? If so, I'll go ahead and close this issue down, but the entire call history/per call/alias things will undergo a comprehensive overhaul at some point in the future, just not entirely sure when.

**Comment by WiredLife** [comment]
@lwvmobile it works! very nice.
would be nice if the tag can be added to the call history and the "Name of Group" can be added to the wav file name and the spaces are replaced with a underscore (_)

can you explain what "DE - Digital Enc" means?

**Comment by lwvmobile** [comment]
Coding it to include the name of the group might be more than I'm wiling to chew off at the moment. Not entirely sure why I didn't include underscores instead of spaces though, I think I meant to do that, but didn't. It's all on the todo list as far as the aforementioned overhaul on per call, so perhaps in a future update, just no ETA on when that might be, not anytime soon.
