### ISSUE TITLE
Protocol Implementation 

### ISSUE THREAD

**Issue by alwinhb** [lwvmobile/dsd-fme#175]
@lwvmobile thank you for the open source code, I needed to understand whether it contains complete protocol implementation DMR [Tier 1 and 2]?

**Comment by lwvmobile** [comment]
No, there are still missing portions of the published ETSI specifications inside of DSD-FME for DMR, I couldn't honestly tell you which all they are at this point, most of them various CSBK PDUs for Tier 3 and so on, and probably some misc things in Tier 1 and Tier 2 that I can't think of at the moment, things like Unified Single Block (LIP) and UDT, but I'd say its good enough for everyday use. Is there anything specifically you are looking for?

**Comment by alwinhb** [comment]
@lwvmobile I am mainly looking for Interleaving/Deinterleaving , BPTC 4FSK and ETSI PDUs (Protocol Data Units) for tier 1 and 2

**Comment by lwvmobile** [comment]
Well, it pretty much does all of those, to what extent it decodes inside of individual PDUs for DMR just depends on what it is, and how specific you wish to be. It might be easier to just use the software and decide what all it can do and what it can't do for you on DMR rather than ask what all is implemented.
