### ISSUE TITLE
Data not showing in D XTRA

### ISSUE THREAD

**Issue by francisuk1989** [lwvmobile/dsd-fme#178]
I dont know much on this topic but i believe **64250** is some sort of Data channe;l whatever is GPS or SMS.

Is this normal?
Shouldn't this be in D XTRA under Call Info? Maybe missing code to say is need to be in the D XTRA
Or is it something new?

```
--Call History----------------------------------------------------------------
| 2023-12-17 11:14:13 TGT [       2] SRC [   64250] DCC [14] [TG2][A]**
| 2023-12-17 11:17:20 TGT [       2] SRC [     130] DCC [14] [TG2][A]
| 2023-12-17 11:17:11 TGT [       2] SRC [     221] DCC [14] [TG2][A]
| 2023-12-17 11:17:06 TGT [       2] SRC [     130] DCC [14] [TG2][A]
| 2023-12-17 11:16:14 TGT [       2] SRC [     221] DCC [14] [TG2][A]
| 2023-12-17 11:16:10 TGT [       2] SRC [   64250] DCC [14] [TG2][A]
------------------------------------------------------------------------------
```

The signal is 55 on SDR++ so is not weak.

Edit
I can see sometimes that
`D XTRA | Data Call - Prop PDU SRC [905] DST [64250]`
is getting used and not showing under Call Info, So maybe missing code?

**Comment by lwvmobile** [comment]
Okay, so I ran your samples. The first sample in the 7z was empty, or rather, no signal. The second sample had RC4 encrypted voice on it, so those do indeed belong in the Call History and not in D XTRA, since they are voice calls. Actually, no data calls are 'supposed' to be in Call History, but I realized that when I do CSBK tuning for Tier 3 systems (and also potentially data calls on Cap+ or XPT) that a value will be assigned in there for that slot, so data calls can show up there on Tier 3. I don't think Tier 2 like that IP Site Connect system sample should trigger the Call History, but I could have something set up in FLC if there are Data Terminators, but I don't see anything obvious at the moment that has that.

Another thing, Data Calls are not persistent in the Ncurses Terminal under D XTRA (by default, anyways) and when frame sync is lost, then they just go away. There is a patch that somebody requested to make all calls persist indefinitely until they change, or the color code changes, and that's available as both a .patch file for source code patching and building, and in the latest release zip folder as an exe file, checking the readme will tell you which one of those it is.

But yeah, usually I see SRC 64250 often on some MotoTRBO systems on data calls, probably some special gateway address they use. The Prop_PDU though is probably indicating encrypted packet data though, so even if there was some data like GPS in there, it's most likely also encrypted (just a hunch)

**Comment by francisuk1989** [comment]
> But yeah, usually I see SRC 64250 often on some MotoTRBO systems on data calls, probably some special gateway address they use. The Prop_PDU though is probably indicating encrypted packet data though, so even if there was some data like GPS in there, it's most likely also encrypted (just a hunch)

Yeah, Is not the first time i seen before with **64250** i have seen them on other systems with Courier's/Delivery services type of transmission and not really a tier 1/single user repeater.

If i remember currently DSDPlus was telling me is a `Radio Check` 

I will close the issue based on encrypted packet. If i see another system doing **64250** without encryption, ill reopen this issue again with a sample, Unless someone eles finds **64250** to compare.

Googling `64250`
https://forums.radioreference.com/threads/just-found-my-first-ever-lrrp-frequency.332867/post-2569957
This what it did.
