### ISSUE TITLE
on windows 11 the dsd-fme -i tcp isnt working

### ISSUE THREAD

**Issue by sefimlog** [lwvmobile/dsd-fme#184]
i have downloaded the latest win32 version.
i tried it on windows 10, and it was working fine, but same version doesnt.
i tried it with sdrpp and sdr# , same results

any idea?

**Comment by lwvmobile** [comment]
Can you clarify which version was working, and which version isn't working for you?
When you say it isn't working, can you be more specific? Does it start up at all? 
Is there a problem with your bat file or startup command?

**Comment by sefimlog** [comment]
ok, on windows 10, i start sdr# or sdrpp, with the option to broadcast the audio over tcp - port 7355. then start dsd-fme with the command lne option -i tcp -N, I i was able to decode the station I was on in sdr#.

this didnt work for me on windows 11.

I hope I am more clear now.

**Comment by lwvmobile** [comment]
Oh, in that case, I would first try to manually specify the address of the localhost. For example:
`dsd-fme -i tcp:127.0.0.1:7355` or perhaps whatever your local ip address is in its place, like `tcp:192.168.7.5:7355`. Also, make sure that SDR++ (or SDR#) is also using that same address in its network sink configuration and is started up and in 'listening' mode to listen for a connection. DSD-FME is only setup internally to handle IP4, so may need to make sure your Windows machine is also setup with IP4 and not just IP6.

Listening and Ready:

![Screenshot from 2023-02-20 20-01-50](https://github.com/lwvmobile/dsd-fme/assets/59371473/46463541-ce00-42da-ae8c-f263049d4504)

Should change to connected when DSD-FME is started and connected:
![Screenshot from 2023-05-09 17-26-27](https://github.com/lwvmobile/dsd-fme/assets/59371473/a166d916-4b03-4849-8d4a-96ab5b54ce95)



If those don't work, you may need to look at your Windows Defender or Firewall settings, make sure both SDR++ or SDR#, and DSD-FME can all access the network so they can communicate. Usually, when you first start up a network feature in those, the popup for if you want to allow those on your network may pop up, but only does so once, so if you hit 'no' on accident, then you'll have to hunt for that and allow it.

**Comment by sefimlog** [comment]
tons of thanks.
with your help I was able to get sdrpp to work again in windows 11.
but still have problem with sdr#
![image](https://github.com/lwvmobile/dsd-fme/assets/141713332/949aed5c-c51e-4e24-9959-5bd14d22e619)

I erased all rulls related to sdr# in the firewall, then restart sdr# and was prompt for the firewall permission. but still it doesnt work

**Comment by sefimlog** [comment]
OK, I will try to supply more details.
First, the sdr# version is v1.00.1855:
![image](https://github.com/lwvmobile/dsd-fme/assets/141713332/c2ea01af-6243-4569-b8b4-d3563c5e6770)

I start the sdr# then click the checkbox ar the stream audio over tcpip:

![image](https://github.com/lwvmobile/dsd-fme/assets/141713332/9b4466c5-5536-4c2f-9e77-72a5aaa5838c)


Then I am running my bat file that contain the line:

dsd-fme.exe -i tcp:127.0.0.1:7355 -N 2>> log.ans

The dsd-fme start, but in the log i get:
Build Version: v2.1b (20230915)
MBElib Version: 1.3.4
CODEC2 Support Enabled
Enabling NCurses Terminal.
TCP Direct Link: 127.0.0.1:7355
ERROR opening socket
OSS Input /dev/dsp.
OSS Output /dev/dsp.
Audio In/Out Device: /dev/dsp


So dsd-fme isnt getting the audio input.

**Comment by lwvmobile** [comment]
So, its working with SDR++ now, and connected to its Network TCP sink, correct? 

But it won't connect to the SDR# 'UDP' Audio stream because its not TCP. That doesn't appear to be the correct plugin. You wan to use the TCP Audio Server. Just as a reminder, the plugins for GPredict(rigctl) and the TCP Audio Server are found in the main zip file in the SDR# Plugins folder.

**Comment by sefimlog** [comment]
Really thanks for the help. I feel I am getting closer to the solution :)

I couldent find the plugin you wrote me. but found this:

![image](https://github.com/lwvmobile/dsd-fme/assets/141713332/42ed9115-d584-4a50-b905-633cc4a9b0a5)

Build Version: v2.1b (20230915)
MBElib Version: 1.3.4
CODEC2 Support Enabled
Enabling NCurses Terminal.
TCP Direct Link: 127.0.0.1:4532
TCP Connection Success!


I have changed the -i tcp:127.0.0.1:4532  and it say "connected" on both sides.  but dsd-fme doesnt show that he receive any data. something is still missing...

Isnt rigctl for changing the frequency from remote?

**Comment by lwvmobile** [comment]
Should be called TCP Audio Server, if you don't already have that plugin installed for SDR#, then you should just have to copy and paste it from the folder in the DSD-FME release zip file into the plugins folder in the SDR# root directory, if not mistaken.  It should be buried somewhere in that burger menu. Jjust make sure the UDP Audio Server (or anything else) isn't already running and blocking the port you are trying to use.

Keep in mind though, issues here are for support and reporting issues for DSD-FME, not for how to set up and use SDR#, and dealing with those issues.

If you were able to connect to the gpredict plugin, it shows that the windows firewall rules aren't blocking that connection, but since we already know that SDR++ connects and works, then we've already established that, and yes, that plugin, or the rigctl protocol is used by DSD-FME to change frequencies when using trunking or scanning options.

**Comment by sefimlog** [comment]
Thats it. all works!
Thank you so much for this support ticket.
I totaly understand it isn't a bug in dsd-fme, just my lack of knoladge.
Hopfully someone will utilize it in the feutue.
