### ISSUE TITLE
Reverse Channel info calculation

### ISSUE THREAD

**Issue by kantooon** [lwvmobile/dsd-fme#187]
Hi, I just want to check something with you regarding RC info calculation in dmr_le.c
Shouldn't the CRC7 only be applied to the first 4 bits? Right now CRC7 seems to be applied both to RC Info bits and CRC bits...
Eg.

```
diff --git a/src/dmr_le.c b/src/dmr_le.c
index dee6925..235f83c 100644
--- a/src/dmr_le.c
+++ b/src/dmr_le.c
@@ -229,7 +229,6 @@ void dmr_sbrc (dsd_opts * opts, dsd_state * state, uint8_t power)
   // 9.3.2 Pre-emption and power control Indicator (PI)
   // 0 - The embedded signalling carries information associated to the same logical channel or the Null embedded message
   // 1 - The embedded signalling carries RC information associated to the other logical channel

   for(i = 0; i < 32; i++) sbrc_interleaved[i] = state->dmr_embedded_signalling[slot][5][i + 8];
   //power == 0 should be single burst
   if (power == 0) irr_err = BPTC_16x2_Extract_Data(sbrc_interleaved, sbrc_return, 0);
@@ -252,8 +251,10 @@ void dmr_sbrc (dsd_opts * opts, dsd_state * state, uint8_t power)
       crc_extracted = crc_extracted | sbrc_return[i+4];
     }
     crc_extracted = crc_extracted ^ 0x7A;
-    crc_computed = crc7((uint8_t *) sbrc_return, 7);
+    crc_computed = crc7((uint8_t *) sbrc_return, 4);
```

**Comment by lwvmobile** [comment]
Yeah, I believe you are correct. The issue is, I don't believe I've ever seen the Reverse Channel on this, its always been the Single Burst, either that, or if its considered the Reverse Channel, its always set null when its there, and the crc would pass either way.  I'll add the change to the next update that I push. I also went ahead and added decoding for the 4-bit PDU that's present, not that its all that exciting of information, but regardless, might as well.

This function is really only super useful for when encryption is in use and you need the late entry enc identifiers found in the single burst, if we are being completely honest though, and the TXI information is only present because I needed to know when it was TXI and not enc information.

The DMR manual doesn't seem to, as far as I remember, tell us explicitly, when you should expect an RC burst and not an SB burst. I was just going on the power/pre-emption indicator, but that may very well be incorrect.

**Comment by kantooon** [comment]
Thanks for the confirmation. For context, I'm testing transmit interrupt and MS power control which use the Reverse Channel PDU.
Reverse channel is indicated by the PI bit in the EMB payload so I think that code is correct.

**Comment by lwvmobile** [comment]
Oh, okay, if you do any testing on that, send the samples my way and I'll see if my code works for the opcodes in the table and so on. 

![Screenshot from 2024-02-03 12-01-16](https://github.com/lwvmobile/dsd-fme/assets/59371473/118e749a-ff73-408a-ac50-268425573933)

**Comment by lwvmobile** [comment]
I pushed a commit for the crc issue, along with the 4-bit pdu element decoder, as well as some revamped p_clear and p_protect tuning logic, so if you get a chance, can you test some of the p_clear and rc stuff out and report back, let me know if it hangs around reliably on the voice channels and data channels when its supposed to properly. Thanks.

**Comment by kantooon** [comment]
Ok, thanks, I will test it.

**Comment by kantooon** [comment]
Tested the RC parsing, it works great. Now if only I could figure out why my radios don't decode it...

**Comment by lwvmobile** [comment]
Couldn't really say on that one. Is that a command that all radios obey, or is it just when its a tight nit T3 system where all the things are meant to work together. From my own research, I've seen where the DMR standard starts to break apart when it comes to some things like the RC and SB single bursts, not to mention the plethora of non-standard CSBKs and Link Control messages used by certain vendors, especially on those CCR radios.

**Comment by lwvmobile** [comment]
Everything good to go on this so we can close it out, or do we need to leave it open for anything?

**Comment by kantooon** [comment]
Yeah, all good, let's close it.
