### ISSUE TITLE
Wav files recording in Tier II DMR

### ISSUE THREAD

**Issue by jammedjackal** [lwvmobile/dsd-fme#265]
Dear All,

I'm trying to set up a headless Linux-based "radio scanning center". For monitoring frequencies I use RTLSDR-Airband, which is doing a marvelous job, and rdio-scanner for UI. I have some Tier II DMR frequencies in my area, which I would like to include as well. I have already figured out how to route audio from RTSSDR-Airband to DSD-FME for DMR decoding, but I'm in a pickle here. My setup for DSD-FME seems to be quite simple, as I would like to decode audio sent from RTLSDR-Airband and save decoded speech as mp3 or wav in particular folder with particular name for rdio-scanner, but I can't find such use case in DSD-FME documentation.

Is it possible to per-call export decoded audio from DSD-FME to specific directory with previously defined filename template?

**Comment by billghunt** [comment]
It's my understanding that lwvmobile is on vacation.  You will probably get more help in the radio reference forums.  This is actually for bugs in this software.

**Comment by jammedjackal** [comment]
Thanks for the tip. One way or another, I keep my fingers crossed for this brilliant software. Wish you best.

**Comment by lwvmobile** [comment]
I'm going to close this as completed since you got some help on the forum regarding this already. Currently, I have no interest in changing or doing any new code or features for DSD-FME, so that string will remain static, but its open source, so anybody can go in and change anything to their liking with a little initiative.
