### ISSUE TITLE
Stolen code ?

### ISSUE THREAD

**Issue by LouisErigHerve** [lwvmobile/dsd-fme#64]
I'm a bit surprised, because after analyzing some part of your DSD-FME code, some functions are very, very similar to my private DSD code (same variables/functions name, same comment, same layout...) and I suspect this code has been stolen...

Example : The PI header decoding function (ProcessDmrPiHeader) is not included in my public version of DSD but in your code I found almost the same code of my private version of DSD, how can you explain it ? Where did you get this code ?

**Comment by iScottybotty** [comment]
LOL.

**Comment by lwvmobile** [comment]
I copy and pasted another function inside of dmr_sync.c to create a lot of the new functions, including the PI header. The code does indeed look similar to other functions of yours, because they are all copy and paste from the same function with different workings. Until right now, I had no idea you had a private version, are you suggesting that I somehow nefariously got a hold of this version? Do you have a private version for sale?

Perhaps instead of randomly accusing me of stealing your 'private' code Louis, you should actually respond to the people who raise issues on the Github page and at least reply to them. 

I'd also like to remind you of the license which your code was distributed under, including the functions inside of dmr_sync.c that I copy and pasted.

 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.

**Comment by lwvmobile** [comment]
Here ya go, it was a copy and paste of the ProcessDmrTerminaisonLC function.

![Screenshot_370](https://user-images.githubusercontent.com/59371473/171295328-2ab32f82-7026-42f7-b485-495d67d1ad97.png)
![Screenshot_371](https://user-images.githubusercontent.com/59371473/171295347-78255969-5a9b-4057-9383-8e1fb0f39383.png)
![Screenshot_372](https://user-images.githubusercontent.com/59371473/171295359-ef1de359-976e-4f80-a8f5-0a24dbc9837a.png)

**Comment by LouisErigHerve** [comment]
Thank you for these explanations and for the screenshot, I understand better now.
