### ISSUE TITLE
audio problem

### ISSUE THREAD

**Issue by sefimr** [lwvmobile/dsd-fme#68]
for 2 days now I am trying to run this software.
it compiled very easy with the install command
i am able to run gqrx with no problem on my vmware ubuntu.
but when trying to run:
dsd -i rtl -o /dev/dsp -c 434.3m -G26 -Y 12
                                 CTRL + C twice to exit 
 ██████╗  ██████╗██████╗     ███████╗███╗   ███╗███████╗                     
 ██╔══██╗██╔════╝██╔══██╗    ██╔════╝████╗ ████║██╔════╝                     
 ██║  ██║╚█████╗ ██║  ██║    █████╗  ██╔████╔██║█████╗                       
 ██║  ██║ ╚═══██╗██║  ██║    ██╔══╝  ██║╚██╔╝██║██╔══╝                       
 ██████╔╝██████╔╝██████╔╝    ██║     ██║ ╚═╝ ██║███████╗                     
 ╚═════╝ ╚═════╝ ╚═════╝     ╚═╝     ╚═╝     ╚═╝╚══════╝                     
Digital Speech Decoder: Florida Man Edition                                  
Github Build Version: v1.6.0-168-g171c71d 
mbelib version 1.3.0
Tuning to frequency: 434300000 Hz
Error, couldn't open /dev/dsp

it is always reporting problem with /dev/dsp

what is the problem?

**Comment by iScottybotty** [comment]
The problem is dev/dsp. Remove dev/dsp and try. 

Failing that, go: pacmd load-module module-null-sink sink_name=virtual_sink  sink_properties=device.description=Virtual_Sink

Then: pavucontrol 
You’ll now be able to pipe the audio wherever. 

When you run FME use: dsd -fr -i rtl -c 434.3M -P -2 -D 1 -G 36 -L 70 -U 6021 -Y 12

i rtl to use rtl_fm (default is -i pulse for pulse audio)

-c Set frequency
-P set PPM error (default = 0)
-D set device index number (default = 0; first device detected)
-G set device gain (0-49) (default = 0 Auto Gain)
-L set rtl squelch to 25 (default = 0; off)
-U set UDP port for rtl_fm remote control (default = 6020)
-Y 12 set rtl VFO bandwidth in kHz, (default = 12)(6, 8, 12, 16, 24, 48)

Hope it helps.

**Comment by lwvmobile** [comment]
Any update on your status with this? Did you need anymore assistance?

**Comment by lwvmobile** [comment]
Issue closed due to inactivity, and the solution already commented.
