### ISSUE TITLE
Question about tcp input (maybe just sdrpp) 

### ISSUE THREAD

**Issue by alphafox02** [lwvmobile/dsd-fme#92]
Just rebuilt your main branch and pulled down a DMR iq file from SDRPlay’s site. I used sdrpp radio out over network with TCP setting, this time around DSD-fme decoded and played the audio perfectly. What I’m having happen though is that when I have sdrpp started and showing listening, the moment DSD-fme starts and starts decoding from the network stream the sdrpp waterfall and fft are basically frozen, it’ll occasionally show a fast movement but for the most part it’s locked solid till I stop DSD-fme.

Just to be clear. Sdrpp isn’t locked up, it’s just the waterfall and fft. Does that happen to anyone else? I haven’t used the network sync in awhile and don’t recall it happening before.

**Comment by alphafox02** [comment]
Also audio over network/tcp out of sdrpp is flawlessly decoded with DSD-fme, however, leaving it on audio and having it come out pulse is not. 

DMR IQ file I’m testing with at the moment is here. 
https://www.sdrplay.com/iq-demo-files/

If there’s a mailing list I’ll ask further questions there, didn’t seem like I could sign up on radio reference.

**Comment by alphafox02** [comment]
One more update, running DSD-FME on another computer on the network and connecting to the network output of sdrpp does still effect the fft/waterfall - like it’s almost ground to a halt but not quite frozen like when running everything on the one desktop.

**Comment by alphafox02** [comment]
Closing as it’s an expected behavior when playing back from file. File source isn’t throttled and when I connect, it’s getting buffered. False alarm. Liking the new updates!

**Comment by lwvmobile** [comment]
I know you've already answered you're own questions (I think) but I'll go over some of these items anyways.

**Fast/Slow/Stopped Waterfall in SDR++.**

I have observed this behavior as well, and can tell you the perfect way to freeze the waterfall. Just open the ncurses menu and wait x number of seconds. What is happening, when it freezes, is that the buffer is completely full and can't hold anymore data. When you exit the ncurses menu, the data inside of FMEs buffer will run a lot faster until it catches up, then it will resume normal speed. If there is voice, it will throttle again because pulse server/audio output is throttling it.

When you are playing back IQ files inside of SDR++, and using Network/TCP, there is no throttle. I did the same thing a wile back and observed the same phenomena.  This is also the exact same behavior that occurs when playing back OP25 or FME symbol capture bin files, it plays data back at an extraordinary speed, and only slows down to play audio back at the correct rate. It that instance, its actually super beneficial so you aren't waiting forever for the voice portions to play back.


> One more update, running DSD-FME on another computer on the network and connecting to the network output of sdrpp does still effect the fft/waterfall - like it’s almost ground to a halt but not quite frozen like when running everything on the one desktop.

I have no idea what's happening there, I have not had the same issue with running both on the same desktop. Which desktop/os environments are you running in each situation? Also, just curious, are you using ethernet on both machines, or do you have wifi. Something to note, is that TCP is guarded against dropped transmissions and will deliver all packets in order, but that comes at the cost of lag if in an environment that can cause lag (i.e., bad wifi). The other consideration is how powerful the computer running SDR++ is, if its a potato (old computer, or low spec machine) then it may have a hard time keeping up with SDR++ and also a large spectrum IQ file, which would need even more CPU/GPU capability than a normal RTL dongle at 1.024 or 2.048 Mhz Bandwidth Spectrum.



> however, leaving it on audio and having it come out pulse is not.

Usually, this would also be just fine, and in the case of IQ playback, might be more ideal since the pulse server itself acts as a throttle. If you are getting bad decodes, it sounds like you haven't set up the virtual sink, or it is not set up properly, in that case, you would want to make sure the output of SDR++ is dumped into a virtual sink (and no other audio going into it) and that FME is listening to the same virtual sink, and that FME's audio is routed out of your normal speaker setup.

---

Okay, a few minutes later, and I grabbed that file you mentioned. Here is the workaround to get normal playback speed on an SDR++ IQ file playback. Just make a second radio VFO (preferably with squelch on), have it go out normal audio, and its throttled now. Ta-da! Also, just an updated observation. I've realized that when decoding IQ files without a throttle, the waterfall does stop, that is because, as mentioned earlier, the TCP buffer is completely full in FME, and it needs to unload all of that data before it can buffer some more.

Video of what's going on:
https://www.youtube.com/watch?v=rTTDyc6e3f4

Also, realized my pulse audio volume control was cut off in the video, so here are images of a proper setup.


![Screenshot from 2022-12-29 02-17-02](https://user-images.githubusercontent.com/59371473/209917860-b2f4c8a8-c809-4bae-991f-6bc545b23c82.png)
![Screenshot from 2022-12-29 02-17-28](https://user-images.githubusercontent.com/59371473/209917874-f5f96dfd-8763-47d2-9e02-1879b4806ff1.png)

And if you have any other questions, feel free to ask them here, no worries. I don't have a mailing list, and the RR forum is overrated anyways lol.

**Comment by lwvmobile** [comment]
Just as an aside, if you use SDR++ with an SDR hardware device, you shouldn't ever experience the 'waterfall' freeze or full buffer, that's just because we are sending as much data to DSD-FME as it can hold since there is no throttle. The hardware itself is a throttle in a sense, as is pulse audio input and output, so data to data is no throttle, data to voice is throttled, hardware to data or voice is throttled. I think that makes sense.

**Comment by lwvmobile** [comment]
Also, just for fun, here is the same mention on SDR++ issues: Its intended behavior.

https://github.com/AlexandreRouma/SDRPlusPlus/issues/688

**Comment by alphafox02** [comment]
I'll try that hack in the video, good to know that's possible. I wonder why it slows it down.

**Comment by lwvmobile** [comment]
> They're both running DragonOS (22.04 Lubuntu based). It's a SDR geared Distro I spend most of my free time putting together.

Okay, I thought you were the DragonOS guy, just thought you had a different username. I just remembered, it was in the Boatbod OP25 issue where you mentioned that. That's fine if you include it, its all open source software anyways, so its fine if its in there. Preferably the 2.0.0.-2 or 2.0.0-3 version, since that's my best foot forward to date, its stable, and can trunk DMR systems well, if nothing else. Still needs more testing on P25 QPSK systems, and NXDN Trunking is completely untested. 

That's the last version I plan to release for quite a while, barring anybody pointing out any major bugs or breaks.

**Comment by alphafox02** [comment]
Also “cemaxecuter”. I’ll try and find some of those other systems. What you could try is the Airspy network, if you’ve not already went that route. Also, the virtual audio cable w/ SigDigger worked great. I like how you included the script cause I’m always forgetting the pacmd command.

**Comment by lwvmobile** [comment]
> That's the last version I plan to release for quite a while, barring anybody pointing out any major bugs or breaks.

Yeah, I say that, and then I remember/notice some little tweak or fix I meant to make, just had to push a little 'cap max' thingy, now its at 2.0.0-4. This is the last time I'll update, I swear, until at least tomorrow lol.

> Also “cemaxecuter”.

Yeah, I get your videos in my recommended feed from time to time, I think I watched the SigDigger video, because I was interested in using it as a better way to demodulate 8 Level QPSK, but I couldn't figure it out properly. Was interested in the idea of having it do the demodulation, and taking the dibit stream and having DSD-FME decode it directly, see if it could do a better job, but never made it very far on that effort.



> I like how you included the script cause I’m always forgetting the pacmd command.

Yeah, I try to make things easy and painless, thus the scripts, I'd never be able to remember a command that long, and I kind of frown on telling users how to modify their systems to make those changes persistent out of fear that they will break something. I thought DragonOS had those types of sinks in it by default. Maybe it was the Skywave distro, can't remember now.

Also, if you need some wav files for testing/verification, etc, I posted some just yesterday for another user, you can play them back in a media player into the virtual sink. Probably a lot more stuff to check out than the IQ sample on a loop.

https://ufile.io/s3xcgj4h
https://ufile.io/easwrm8h

Just a heads up though, the Hytera sample isn't great, so don't expect excellent decoding on that one.

**Comment by alphafox02** [comment]
It was late when I recorded, but hopefully I didn’t butcher the DSDFME setup. I mainly wanted to make sure people updated things from main and see how the SDR++ network sink and virtual audio syncs w/ SigDigger. Check out the latest video if you get time.

There’s also some new features, one of which I mention in the video, but there’s more to come for SigDigger you may like. I once had the developer walk me through qpsk (I think) and a file he provided, I’ll have to go find those steps.
