### ISSUE TITLE
Cygwin compile issue after upgrading Cygwin packages

### ISSUE THREAD

**Issue by LouisErigHerve** [lwvmobile/dsd-fme#97]
Hello lwmobile

Thanks for the nice job you made on DSD-FME.

I would like to inform you that this morning I updated many of my Cygwin packages (in 64 bits version), and I was not able to compile any DSD program after the upgrade (same issue on your DSD and on mine).

I got an error `#include <stdlib.h> - No such file or directory` on all files.

The issue seems to come from the CMake files, so I reorganized my `CMakeLists.txt` file and now the build is OK.

By using DSD-FME I was able to compile the code only by modifying the `CMakeLists.txt` and the `FindLibSndFile.cmake` files.

I don’t know if I’m alone in this case but if someone else encounters the same problem as me the following 2 files can be used to build DSD-FME:

[FindLibSndFile.cmake.txt](https://github.com/lwvmobile/dsd-fme/files/10366761/FindLibSndFile.cmake.txt)
[CMakeLists.txt](https://github.com/lwvmobile/dsd-fme/files/10366763/CMakeLists.txt)

Rename the `FindLibSndFile.cmake.txt` file into `FindLibSndFile.cmake`

Note : I tried to copy/paste the content of both files here but the content preview gives me something unreadable.

Is anyone else having the same problem as me with the latest Cygwin packages?

**Comment by romanremus** [comment]
hello Eric.....I use cygwin both for your version of dsd and the dsd-fme version....and whenever something new appears on github I do copy paste.....and the recompilation apples perfect ....cygwin on 64 bits ....but how do you upgrade to cgwin?

**Comment by LouisErigHerve** [comment]
To update Cygwin package I use the [setup-x86_64.exe](https://www.cygwin.com/setup-x86_64.exe) and follow the process

New update appear on the list.

![Cygwin Update Package](https://user-images.githubusercontent.com/6905505/211171006-9a2eabe0-99f9-4fba-8386-66a5e7936d90.png)

I do it regularly to be sure to have the latest versions of GCC, Make, CMake, libs...

But sometimes new packages introduce some bugs (for example I stay on the GDB version 9.2-1 because all new versions uses invalid path with Eclipse and make debugging impossible)

Did you update your Cygwin packages ?

**Comment by romanremus** [comment]
I think I'm making a mistake in installing new packages in cygwin......I use these commands that update themselves, I thought the packages 
./setup-x86_64.exe --no-desktop --no-shortcuts --no-startmenu --quiet-mode 
./setup-x86_64.exe c:\cygwin64 -q --upgrade-also 
apt-cyg update

    Pe sâmbătă, 7 ianuarie 2023, 23:42:11 EET, Louis-Erig HERVE ***@***.***> a scris:  
 
 


To update Cygwin package I use the setup-x86_64.exe and follow the process

New update appear on the list.



I do it regularly to be sure to have the latest versions of GCC, Make, CMake, libs...

But sometimes new packages introduce some bugs (for example I stay on the GDB version 9.2-1 because all new versions uses invalid path with Eclipse and make debugging impossible)

Did you update your Cygwin packages ?

**Comment by romanremus** [comment]
if you install this......wget https://raw.githubusercontent.com/transcode-open/apt-cyg/master/apt-cyg/master/apt-cyg
chmod +x apt-cyg
mv apt-cyg /usr/bin
 you will be able to install the packages in cygwin like this: apt-cyg install (something) (something)    Pe duminică, 8 ianuarie 2023, 00:03:21 EET, ***@***.*** ***@***.***> a scris:  
 
  I think I'm making a mistake in installing new packages in cygwin......I use these commands that update themselves, I thought the packages 
./setup-x86_64.exe --no-desktop --no-shortcuts --no-startmenu --quiet-mode 
./setup-x86_64.exe c:\cygwin64 -q --upgrade-also 
apt-cyg update

    Pe sâmbătă, 7 ianuarie 2023, 23:42:11 EET, Louis-Erig HERVE ***@***.***> a scris:  
 
 


To update Cygwin package I use the setup-x86_64.exe and follow the process

New update appear on the list.



I do it regularly to be sure to have the latest versions of GCC, Make, CMake, libs...

But sometimes new packages introduce some bugs (for example I stay on the GDB version 9.2-1 because all new versions uses invalid path with Eclipse and make debugging impossible)

Did you update your Cygwin packages ?

**Comment by LouisErigHerve** [comment]
Interesting, thanks for the link to emulate an _apt_ package manager, I've ever heard about it but I never install it.

As I see you are using the `setup-x86_64` file in command line mode, this is another approach, I don't use it, preferring the GUI method, more comfortable for the installation process, but every people make as they want...

To come back to the initial issue, what is your current **GCC** version ? Mine is **11.3.0**
**CMake version is 3.23.2**
**Make version is 4.4**

I think this could be the root cause of the compiler issue...

**Comment by romanremus** [comment]
Eric ..... I have exactly the same package versions as you ... I don't understand why you have an error, when I had a cygwin error ... I deleted the whole cygwin folder and installed everything from 0 ..... if you want, I will also send you a link where you will find a notepad ...... and there I installed a lot of packages, because I use cygwin in several software ..... some packages they will give an error..but nothing.....you install everything further: link ***** https://ufile.io/a8p90oj6

    Pe duminică, 8 ianuarie 2023, 00:26:40 EET, Louis-Erig HERVE ***@***.***> a scris:  
 
 


Interesting, thanks for the link to emulate an apt package manager, I've ever heard about it but I never install it.

As I see you are using the setup-x86_64 file in command line mode, this is another approach, I don't use it, preferring the GUI method, more comfortable for the installation process, but every people make as they want...

To come back to the initial issue, what is your current GCC version ? Mine is 11.3.0
CMake version is 3.23.2
Make version is 4.4

I think this could be the root cause of the compiler issue...

**Comment by LouisErigHerve** [comment]
OK, maybe I made an error...

I personally not understand why this compiler issue appear... (I just updated my package, no code changed, but after wasting some time to re-arrange the CMakeList files the issue disappear and now I'm able to build normally).

If nobody have the same issue we can probably close this issue.
